go.property("points", 0)

local function done(self, url, property)
	go.delete()
end

function init(self)
	local pointsstr = tostring(self.points)
	if self.points > 0 then 
		pointsstr = "+"..pointsstr
		go.set("#label", "color", vmath.vector4(0.2, 0.6, 0.2, 1))
	end
	label.set_text("#label", pointsstr)
	msg.post("#sprite", "play_animation", { id = hash("explode") })
	go.animate(go.get_id(), "position.y", go.PLAYBACK_ONCE_FORWARD, go.get_position().y + 200, go.EASING_OUTCUBIC, 2, 0, done)
end